//
// Created by Daniel Mints on 12/18/21.
//

#ifndef PROBABILITY_THEORY_CALCULATOR_CHAR_FUNC_H
#define PROBABILITY_THEORY_CALCULATOR_CHAR_FUNC_H


class char_func {

};


#endif //PROBABILITY_THEORY_CALCULATOR_CHAR_FUNC_H
