//
// Created by Daniel Mints on 12/18/21.
//

#ifndef PROBABILITY_THEORY_CALCULATOR_EXPECTED_VAL_H
#define PROBABILITY_THEORY_CALCULATOR_EXPECTED_VAL_H


class expected_val {

};


#endif //PROBABILITY_THEORY_CALCULATOR_EXPECTED_VAL_H
