//
// Created by Daniel Mints on 12/18/21.
//

#ifndef PROBABILITY_THEORY_CALCULATOR_VARIANCE_H
#define PROBABILITY_THEORY_CALCULATOR_VARIANCE_H


class variance {

};


#endif //PROBABILITY_THEORY_CALCULATOR_VARIANCE_H
